統計基礎の内容をライブラリ未使用とライブラリ使用でメモ

In [2]:
import numpy as np
x = np.array([72,69,57,69,60,69,54,66,51,66])
y = np.array([42,72,57,30,60,18,27,9,45,33])
#平均
mean_x = sum(x)/len(x)
mean_y = sum(y)/len(y)
np.mean(x)
#分散
var_x = sum((xi - mean_x)**2 for xi in x) / len(x) 
var_y = sum((yi - mean_y)**2 for yi in y) / len(y) 
np.var(x)
#標準偏差
std_x = var_x**(1/2)
std_y = var_y**(1/2)
np.std(x) 
#共分散(標本ならn-1、母集団ならnで割る)
var_xy = sum((xi - mean_x)*(yi - mean_y) for xi,yi in zip(x,y)) / len(x)
np.cov(x,y,ddof=0)   #ddof=自由度
#相関係数
coef_xy = var_xy/(std_x*std_y)
np.corrcoef(x, y)

array([[ 1.        , -0.15407971],
       [-0.15407971,  1.        ]])

In [19]:
#データの標準化(平均0分散1に変換)
from sklearn.preprocessing import StandardScaler
data = np.array([72,69,57,69,60,69,54,66,51,66])

standard_data = np.array(list(map(lambda x: (x-data.mean())/data.std(),data)))  #ライブラリ未使用

ss = StandardScaler()
standard_data2 = ss.fit_transform(data.reshape(-1, 1)) #ライブラリ使用

print(standard_data)
print(standard_data2)

[ 1.26086957  0.82608696 -0.91304348  0.82608696 -0.47826087  0.82608696
 -1.34782609  0.39130435 -1.7826087   0.39130435]
[[ 1.26086957]
 [ 0.82608696]
 [-0.91304348]
 [ 0.82608696]
 [-0.47826087]
 [ 0.82608696]
 [-1.34782609]
 [ 0.39130435]
 [-1.7826087 ]
 [ 0.39130435]]


In [44]:
#相関行列
z = np.array([[2,5,8,],[1,5,2,],[9,4,10],[7,13,4]])
C = np.corrcoef(z)
print(C)

[[ 1.          0.24019223  0.15554275 -0.32732684]
 [ 0.24019223  1.         -0.92155064  0.83862787]
 [ 0.15554275 -0.92155064  1.         -0.98432414]
 [-0.32732684  0.83862787 -0.98432414  1.        ]]
